 _format_version: "3.0"
# _transform: true

 services:
    - name: geoserver
      url: http://geoserver:8080/geoserver
      routes:
        - name: geoserver-route
          paths:
            - /geoserver
          methods:
            - GET
            - POST
            - PUT
            - DELETE
          plugins:
            - name: response-transformer
              config:
                add:
                  headers:
                    - "Access-Control-Allow-Origin:*"
                    - "Access-Control-Allow-Headers:*"
                    - "Access-Control-Allow-Methods: GET, PUT, POST, DELETE, HEAD"
        - name: geoserver-option-route
          paths:
            - /geoserver
          methods:
            - OPTIONS
          plugins:
            - name: request-termination
              config:
                status_code: 200
            - name: response-transformer
              config:
                add:
                  headers:
                    - "Access-Control-Allow-Origin:*"
                    - "Access-Control-Allow-Headers:*"
                    - "Access-Control-Allow-Methods: GET, PUT, POST, DELETE, HEAD"
