networks:
  webgis_net:
    name: webgis_net
    driver: bridge

include:
  - ./geoserver/geoserver.yml
  - ./postgresql/postgresql.yml
  - ./redis/redis.yml
  - ./rabbitmq/rabbitmq.yml
  - ./artifact_serve/artifact_serve.yml
  - ./streamer/streamer.yml