version: 2.1

jobs:
  test:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Setup Tests
          command: echo Setup tests is not available for now
  build:
    # Machine Executor - Ref: https://circleci.com/docs/using-linuxvm/
    machine:
      image: ubuntu-2004:current
      resource_class: medium
    steps:
      - checkout
      - run:
          name: Build Artifacts & Deploy
          command: ./infra.sh setup; ./infra.sh down
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy Images
          command: echo Deployment is not available for now.

workflows:
  all_tests:
    jobs:
      - build