version: 2.1

jobs:
  test:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Setup Tests
          command: echo Setup tests is not available for now
  build:
    docker:
      - image: cimg/node:20.15.0
    steps:
      - checkout
      - run:
          name: Build WebApp
          command: src/webapp/build.sh
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy Images
          command: echo Deployment is not available for now.

workflows:
  all_tests:
    jobs:
      - build