version: 2.1

jobs:
  test:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Setup Tests
          command: echo Setup tests is not available for now
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Build Images
          command: echo Building images is not available for now.
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy Images
          command: echo Deployment is not available for now.

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test