services:
  ingester:
    build: ./ingester
    image: ingester:0.1
    container_name: ingester
    volumes:
      - ../../:/data
    networks:
      - webgis_net
    command:
      ["python3", "/data/src/ingester/ingrun.py"]