services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.25.1
    container_name: geoserver
    environment:
      - SKIP_DEMO_DATA=true
      - ROOT_WEBAPP_REDIRECT=true
      - CORS_ENABLED=true
    volumes:
      - ./data/:/opt/geoserver_data/
    networks:
      - webgis_net
    ports:
      - 8080:8080
    restart: always