services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.25.1
    container_name: geoserver
    environment:
      - SKIP_DEMO_DATA=true
      - ROOT_WEBAPP_REDIRECT=true
      - CORS_ENABLED=true
      - JAVA_OPTS=-XX:+UseG1GC -Xms2g -Xmx4g
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=importer
    volumes:
      - ./data/:/opt/geoserver_data/
    networks:
      - webgis_net
    ports:
      - 8080:8080
    restart: always
