services:
  redis:
    image: redis
    container_name: redis
    networks:
      - webgis_net
    ports:
      - 6379:6379
    restart: always

  redis_gui:
    image: redis/redisinsight:latest
    container_name: redis_gui
    networks:
      - webgis_net
    ports:
      - 8082:5540
    volumes:
      - ./data/redisinsight:/data
    restart: always